version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
  jobs:
    post_checkout:
      # Get all tags, needed by versioneer
      - git fetch --unshallow
      # Cancel building pull requests when there aren't changed in the docs
      # directory or in this configuration file (.readthedocs.yaml).
      # READTHEDOCS_VERSION_TYPE is "external" for pull requests.
      #
      # If there are no changes (git diff exits with 0) we force the command
      # to return with 183. This is a special exit code on Read the Docs that
      # will cancel the build immediately.
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yaml
        then
          exit 183
        fi
    pre_install:
      # Avoid having a dirty git index, needed by versioneer
      - git update-index --assume-unchanged docs/conf.py

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt

formats:
  - htmlzip
  - pdf
  - epub
