__correct_traceid_dict__={
	'CL.AGE  00..E'  : 'CL.AGE.00.EHE',
	'CL.AGE  00..N'  : 'CL.AGE.00.EHN',
	'CL.AGE  00..Z'  : 'CL.AGE.00.EHZ',
        '.AGE..EHZ'      : 'CL.AGE.00.EHE',
        '.AGE..EHN'      : 'CL.AGE.00.EHN',
        '.AGE..EHE'      : 'CL.AGE.00.EHZ',
	'CL.AGEO.--.EHE' : 'CL.AGEO.00.EHE',
	'CL.AGEO.--.EHN' : 'CL.AGEO.00.EHN',
	'CL.AGEO.--.EHZ' : 'CL.AGEO.00.EHZ',
	'CL.TRZ  00..Z'  : 'CL.TRZ.00.EHZ',
	'CL.TRZ  00..N'  : 'CL.TRZ.00.EHN',
	'CL.TRZ  00..E'  : 'CL.TRZ.00.EHE',
	'CL.AIO  00..E'  : 'CL.AIO.00.EHE',
	'CL.AIO  00..N'  : 'CL.AIO.00.EHN',
	'CL.AIO  00..Z'  : 'CL.AIO.00.EHZ',
	'CL.AIO.--.EHE'  : 'CL.AIOA.00.EHE',
        'CL.AIO.--.EHN'  : 'CL.AIOA.00.EHN',
        'CL.AIO.--.EHZ'  : 'CL.AIOA.00.EHZ',
	'CL.AIOA.--.EHE'  : 'CL.AIOA.00.EHE',
	'CL.AIOA.--.EHN'  : 'CL.AIOA.00.EHN',
	'CL.AIOA.--.EHZ'  : 'CL.AIOA.00.EHZ',
	'.AIO..EHZ'      : 'CL.AIO.00.EHE',
        '.AIO..EHN'      : 'CL.AIO.00.EHN',
        '.AIO..EHE'      : 'CL.AIO.00.EHZ',
	'CL.ALI  00..E'  : 'CL.ALI.00.EHE',
	'CL.ALI  00..N'  : 'CL.ALI.00.EHN',
	'CL.ALI  00..Z'  : 'CL.ALI.00.EHZ',
	'CL.ALI.00.EHZ'  : 'CL.ALI.00.EHZ',
	'CL.ALI.00.EHN'  : 'CL.ALI.00.EHN',
	'CL.ALI.00.EHE'  : 'CL.ALI.00.EHE',
	'.ALI..EHZ'      : 'CL.ALI.00.EHE',
        '.ALI..EHN'      : 'CL.ALI.00.EHN',
        '.ALI..EHE'      : 'CL.ALI.00.EHZ',
	'CL.ALI.--.EHE' : 'CL.ALI.00.EHE',
        'CL.ALI.--.EHN' : 'CL.ALI.00.EHN',
        'CL.ALI.--.EHZ' : 'CL.ALI.00.EHZ',
	'CL.ALIK.--.EHE' : 'CL.ALIK.00.EHE',
	'CL.ALIK.--.EHN' : 'CL.ALIK.00.EHN',
	'CL.ALIK.--.EHZ' : 'CL.ALIK.00.EHZ',
	'CL.DIM  00..E'  : 'CL.DIM.00.EHE',
	'CL.DIM  00..N'  : 'CL.DIM.00.EHN',
	'CL.DIM  00..Z'  : 'CL.DIM.00.EHZ',
	'CL.DIM.--.EHZ'    : 'CL.DIM.00.EHZ',
        'CL.DIM.--.EHN'    : 'CL.DIM.00.EHN',
        'CL.DIM.--.EHE'    : 'CL.DIM.00.EHE',
	'CL.DIMT.--.EHZ'    : 'CL.DIMT.00.EHZ',
	'CL.DIMT.--.EHN'    : 'CL.DIMT.00.EHN',
	'CL.DIMT.--.EHE'    : 'CL.DIMT.00.EHE',
	'.DIM..EHZ'      : 'CL.DIM.00.EHE',
        '.DIM..EHN'      : 'CL.DIM.00.EHN',
        '.DIM..EHE'      : 'CL.DIM.00.EHZ',
	'CL.KOU  00..E'  : 'CL.KOU.00.EHE',
	'CL.KOU  00..N'  : 'CL.KOU.00.EHN',
	'CL.KOU  00..Z'  : 'CL.KOU.00.EHZ',
	'.KOU..EHZ'      : 'CL.KOU.00.EHE',
        '.KOU..EHN'      : 'CL.KOU.00.EHN',
        '.KOU..EHE'      : 'CL.KOU.00.EHZ',
	'CL.PAN  00..E'  : 'CL.PAN.00.EHE',
	'CL.PAN  00..N'  : 'CL.PAN.00.EHN',
	'CL.PAN  00..Z'  : 'CL.PAN.00.EHZ',
	'CL.PAN.--.EHZ'      : 'CL.PAN.00.EHE',
        'CL.PAN.--.EHN'      : 'CL.PAN.00.EHN',
        'CL.PAN.--.EHE'      : 'CL.PAN.00.EHZ',
	'CL.PANR.--.EHZ'      : 'CL.PANR.00.EHE',
        'CL.PANR.--.EHN'      : 'CL.PANR.00.EHN',
        'CL.PANR.--.EHE'      : 'CL.PANR.00.EHZ',
	'CL.PSA  00..E'  : 'CL.PSA.00.EHE',
	'CL.PSA  00..N'  : 'CL.PSA.00.EHN',
	'CL.PSA  00..Z'  : 'CL.PSA.00.EHZ',
	'CL.PSA.--.EHE'  : 'CL.PSA.00.EHE',
        'CL.PSA.--.EHN'  : 'CL.PSA.00.EHN',
        'CL.PSA.--.EHZ'  : 'CL.PSA.00.EHZ',
	'CL.PSAR.--.EHE'  : 'CL.PSAR.00.EHE',
        'CL.PSAR.--.EHN'  : 'CL.PSAR.00.EHN',
        'CL.PSAR.--.EHZ'  : 'CL.PSAR.00.EHZ',
	'.PSA..EHZ'      : 'CL.PSA.00.EHE',
        '.PSA..EHN'      : 'CL.PSA.00.EHN',
        '.PSA..EHE'      : 'CL.PSA.00.EHZ',
	'CL.PYR  00..E'  : 'CL.PYR.00.EHE',
	'CL.PYR  00..N'  : 'CL.PYR.00.EHN',
	'CL.PYR  00..Z'  : 'CL.PYR.00.EHZ',
        'CL.PYR.--.EHE'  : 'CL.PYR.00.EHE',
        'CL.PYR.--.EHN'  : 'CL.PYR.00.EHN',
        'CL.PYR.--.EHZ'  : 'CL.PYR.00.EHZ',
	'CL.PYRG.--.EHE'  : 'CL.PYRG.00.EHE',
        'CL.PYRG.--.EHN'  : 'CL.PYRG.00.EHN',
        'CL.PYRG.--.EHZ'  : 'CL.PYRG.00.EHZ',
	'.PYR..EHZ'      : 'CL.PYR.00.EHE',
        '.PYR..EHN'      : 'CL.PYR.00.EHN',
        '.PYR..EHE'      : 'CL.PYR.00.EHZ',
	'CL.TEM  00..E'  : 'CL.TEM.00.EHE',
	'CL.TEM  00..N'  : 'CL.TEM.00.EHN',
	'CL.TEM  00..Z'  : 'CL.TEM.00.EHZ',
	'.TEM..EHZ'      : 'CL.TEM.00.EHE',
        '.TEM..EHN'      : 'CL.TEM.00.EHN',
        '.TEM..EHE'      : 'CL.TEM.00.EHZ',
        'CL.ROD3.--.HHE'      : 'CL.ROD3.00.HHE',
        'CL.ROD3.--.HHN'      : 'CL.ROD3.00.HHN',
        'CL.ROD3.--.HHZ'      : 'CL.ROD3.00.HHZ',
        '.TRIZ..HHZ'     : 'CL.TRIZ.00.HHZ',
        '.TRIZ..HHN'     : 'CL.TRIZ.00.HHN',
        '.TRIZ..HHE'     : 'CL.TRIZ.00.HHE',
	'CL.TRIZ.--.HHZ' : 'CL.TRIZ.00.HHZ',
        'CL.TRIZ.--.HHN' : 'CL.TRIZ.00.HHN',
        'CL.TRIZ.--.HHE' : 'CL.TRIZ.00.HHE',
	'CL.ZIRI.--.HHZ' : 'CL.ZIRI.00.EHZ',
        'CL.ZIRI.--.HHN' : 'CL.ZIRI.00.EHN',
        'CL.ZIRI.--.HHE' : 'CL.ZIRI.00.EHE',
	'CL.ZIRI.--.EHZ' : 'CL.ZIRI.00.EHZ',
        'CL.ZIRI.--.EHN' : 'CL.ZIRI.00.EHN',
        'CL.ZIRI.--.EHE' : 'CL.ZIRI.00.EHE',
        '.KALI..HHZ'     : 'HA.KALE.00.HHZ',
        '.KALI..HHN'     : 'HA.KALE.00.HHN',
        '.KALI..HHE'     : 'HA.KALE.00.HHE',
	'HA.KALE.--.HHZ' : 'HA.KALE.00.HHZ',
        'HA.KALE.--.HHN' : 'HA.KALE.00.HHN',
        'HA.KALE.--.HHE' : 'HA.KALE.00.HHE',
        '.LAKK..HHZ'     : 'HA.LAKA.00.HHZ',
        '.LAKK..HHN'     : 'HA.LAKA.00.HHN',
        '.LAKK..HHE'     : 'HA.LAKA.00.HHE',
	'HA.LAKA..HHE'   : 'HA.LAKA.00.HHE',
	'HA.LAKA..HHN'   : 'HA.LAKA.00.HHN',
	'HA.LAKA..HHZ'   : 'HA.LAKA.00.HHZ',
	'HA.LAKA.--.HHE'  : 'HA.LAKA.00.HHE',
        'HA.LAKA.--.HHN'  : 'HA.LAKA.00.HHN',
        'HA.LAKA.--.HHZ'  : 'HA.LAKA.00.HHZ',
	'.SERG..HHE'     : 'HP.SERG.00.HHE',
	'.SERG..HHN'     : 'HP.SERG.00.HHN',
	'.SERG..HHZ'     : 'HP.SERG.00.HHZ',
	'HP.SERG..HHZ'   : 'HP.SERG.00.HHZ',
	'HP.SERG..HHN'   : 'HP.SERG.00.HHN',
	'HP.SERG..HHE'   : 'HP.SERG.00.HHE',
	'HP.SERG.--.HHZ' : 'HP.SERG.00.HHZ',
        'HP.SERG.--.HHN' : 'HP.SERG.00.HHN',
        'HP.SERG.--.HHE' : 'HP.SERG.00.HHE'
}
