# -*- coding: utf8 -*-
# SPDX-License-Identifier: CECILL-2.1
"""
Compute mean station residuals from source_spec output.

:copyright:
    2013-2014 Claudio Satriano <satriano@ipgp.fr>,
              Agnes Chounet <chounet@ipgp.fr>

    2015-2026 Claudio Satriano <satriano@ipgp.fr>.
              Kris Vanneste <kris.vanneste@oma.be>
:license:
    CeCILL Free Software License Agreement v2.1
    (http://www.cecill.info/licences.en.html)
"""
import sys
import os
from glob import glob
from collections import defaultdict
from argparse import ArgumentParser
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection
import matplotlib.colors as mcolors
from sourcespec._version import get_versions
from sourcespec.spectrum import read_spectra, SpectrumStream
from sourcespec.ssp_util import mag_to_moment
matplotlib.use('Agg')  # NOQA


# ---- CLI ARGUMENTS


def _parse_args():
    """
    Parse command line arguments.
    """
    parser = ArgumentParser(
        description='Compute mean station residuals from source_spec output.')
    parser.add_argument(
        '-m', '--min_spectra', dest='min_spectra', type=int, action='store',
        default='20', help='minimum number of spectra to '
        'compute residuals (default=20)', metavar='NUMBER'
    )
    parser.add_argument(
        '-r', '--runid', dest='runid', action='store',
        default=None, metavar='RUNID',
        help='select a specific run when multiple runs exist for the same '
             'event. If omitted, residuals will be computed using all '
             'available runs. You can provide a specific RUNID or use '
             '"latest" or "earliest" to select the most recent or the '
             'earliest run, based on alphabetical or numerical order. '
             'If provided, the runid will be also used to create a '
             'subdirectory within the output directory, unless the '
             'provided output directory name (see option "--outdir") is '
             'already the runid.'
    )
    parser.add_argument(
        '-o', '--outdir', dest='outdir', action='store',
        default='sspec_residuals',
        help='output directory (default="sspec_residuals")'
    )
    parser.add_argument(
        '-e', '--exclude', dest='exclude_subdirs', action='append',
        default=None,
        help='subfolder to exclude (repeat for multiple subfolders)'
    )
    parser.add_argument(
        '-p', '--plot', dest='plot', action='store_true',
        default=False, help='save residuals plots to file'
    )
    parser.add_argument(
        '-w', '--weighting', dest='weighting', action='store_true',
        default=False,
        help='multiply each spectrum by its per-frequency spectral '
             'weight (confidence-weighted average) when computing '
             'the mean residual. Falls back to unit weights if '
             'unavailable'
    )
    parser.add_argument(
        '-y', '--yrange', dest='yrange', nargs=2, type=float,
        action='store', default=[-2.5, 2.5],
        help='min/max range for Y axis (default: -2.5, 2.5)'
    )
    parser.add_argument(
        'residual_files_dir',
        help='path to a directory containing SourceSpec residual files in '
             'HDF5 format. Files may be organized in subdirectories '
             '(e.g., by event). You may use wildcards to match specific '
             'subdirectories — remember to quote them to avoid shell '
             'expansion. Example: "sspec_out/*/run1/"'
    )
    return parser.parse_args()


# ---- RESIDUAL I/O


def _filter_by_runid(residual_dict, runid='latest'):
    """
    Filter the residual dictionary by the specified runid criteria.

    Parameters
    ----------
    residual_dict : dict
        Dictionary containing residuals for each station.
    runid : str
        Criteria to select the runid. Can be 'latest', 'earliest',
        or a specific runid.

    Returns
    -------
    filt_residual_dict : dict
        Dictionary containing residuals filtered by the specified criteria.
    """
    if runid is None:
        return residual_dict
    # Residuals generated by older versions of SourceSpec may not have a runid
    # attribute. In this case, we cannot filter by runid.
    if not all(
        hasattr(spec.stats, 'runid')
        for spec_st in residual_dict.values()
        for spec in spec_st
    ):
        print(
            'Warning: not all residuals have a "runid" attribute. '
            'Filtering by runid will not be applied.'
        )
        return residual_dict
    if not isinstance(runid, str):
        raise ValueError('runid must be a string.')
    filt_residual_dict = defaultdict(SpectrumStream)
    if runid not in ['latest', 'earliest']:
        for spec_st in residual_dict.values():
            # Filter by specific runid
            filt_residual_dict[spec_st[0].id].extend(
                [spec for spec in spec_st if spec.stats.runid == runid]
            )
        return filt_residual_dict
    # Filter by latest or earliest runid
    for spec_st in residual_dict.values():
        evids_runids = [
            (spec.stats.event.event_id, spec.stats.runid)
            for spec in spec_st
        ]
        # Dictionary to store the selected runid for each evid
        selected_runids = {}
        for _evid, _runid in evids_runids:
            if runid == 'latest':
                selected_runids[_evid] = max(
                    selected_runids.get(_evid, '0'), _runid, key=int)
            elif runid == 'earliest':
                selected_runids[_evid] = min(
                    selected_runids.get(_evid, '999999'), _runid, key=int)
        # Convert back to list of tuples
        filtered_evids_runids = list(selected_runids.items())
        filt_residual_dict[spec_st[0].id].extend(
            [spec for spec in spec_st
                if (spec.stats.event.event_id, spec.stats.runid)
                in filtered_evids_runids]
        )
    return filt_residual_dict


def _read_residuals_from_dir(
        residual_dict, resfiles_dir, exclude_subdirs=None):
    """
    Read residuals from HDF5 files from a specified directory and all its
    subdirectories.

    Parameters
    ----------
    residual_dict : dict
        Dictionary to store residuals for each station.
    resfiles_dir : str
        Directory containing source_spec residual files in HDF5 format.
        Residual files can be in subdirectories (e.g., a subdirectory for
        each event).
    exclude_subdirs: list of str
        List of subdirectories (potentially containing residual files)
        that should not be parsed
        (default: None, which means all subdirectories are parsed).
    """
    if exclude_subdirs is None:
        exclude_subdirs = []
    if not os.path.exists(resfiles_dir):
        print(f'Skipping directory: {resfiles_dir}: does not exist')
    resfiles = []
    for root, _dirs, files in os.walk(resfiles_dir):
        _dirs[:] = [d for d in _dirs if d not in exclude_subdirs]
        resfiles.extend(
            os.path.join(root, file)
            for file in files
            if file.endswith('residuals.hdf5')
        )
    if not resfiles:
        print(f'No residual file found in directory: {resfiles_dir}')
    for resfile in sorted(resfiles):
        print(f'Found residual file: {resfile}')
        try:
            residual_st = read_spectra(resfile)
        except Exception as e:
            print(f'Error reading residual file: {resfile}: {e}. Skipping.')
            continue
        for spec in residual_st:
            residual_dict[spec.id].append(spec)


def _read_residuals(resfiles_dir, runid=None, exclude_subdirs=None):
    """
    Read residuals from HDF5 files from a specified directory and all its
    subdirectories. The directory can be specified using wildcards.

    Parameters
    ----------
    resfiles_dir : str
        Directory containing source_spec residual files in HDF5 format.
        Residual files can be in subdirectories (e.g., a subdirectory for
        each event). The subdirectory names can be specified using wildcards.
    runid : str
        Only select residuals with the specified runid. If 'latest' or
        'earliest', select the most recent or the earliest runid,
        respectively. If None, select all residuals.
        (default: None)
    exclude_subdirs: list of str
        List of subdirectories (potentially containing residual files)
        that should not be parsed
        (default: None, which means all subdirectories are parsed).

    Returns
    -------
    residual_dict : dict
        Dictionary containing residuals for each station.
    """
    if exclude_subdirs is None:
        exclude_subdirs = []
    residual_dict = defaultdict(SpectrumStream)
    for _resfiles_dir in glob(resfiles_dir):
        _read_residuals_from_dir(
            residual_dict,
            _resfiles_dir,
            exclude_subdirs=exclude_subdirs
        )
    return _filter_by_runid(residual_dict, runid)


# ---- RESIDUAL COMPUTATION


def _compute_station_mean(res_list, weight_by_key, freq_array, use_weights):
    r"""
    Compute the mean residual for a single station.

    For each frequency point, the mean is computed as:

    .. math::

        \\bar{x}(f) = \\frac{1}{N} \\sum_{i=1}^{N} w_i(f) \\, x_i(f)

    where :math:`N` is the number of spectra, :math:`x_i(f)` is the
    residual value of the i-th spectrum at frequency :math:`f`, and
    :math:`w_i(f)` is the spectral weight (or 1 if ``use_weights`` is
    False or no weight is available for the i-th spectrum).
    NaN residual values are treated as zero.

    Note that this is not a standard weighted mean (which would divide
    by the sum of weights). Here the denominator is always :math:`N`,
    so the formula computes a **confidence-weighted average**: each
    :math:`w_i(f) \\in [0, 1]` is both per-spectrum and per-frequency.
    As a result:

    - The output can never exceed the standard arithmetic mean
      (since :math:`w_i(f) \\le 1`).
    - A spectrum with low weight at a given frequency contributes less
      to the numerator but still counts toward :math:`N`, penalizing
      the average for including unreliable data at that frequency.
    """
    spec_mean = None
    weights_used = False
    for spec in res_list:
        spec_interp = spec.copy()
        spec_interp.interp_data_to_new_freq(freq_array)
        # uniform weight to start with,
        # will be multiplied by spectral weights if available
        weight_total = np.ones_like(spec_interp.data_mag)
        if use_weights:
            evid = spec.stats.event.get('event_id')
            key = (spec.id, spec.stats.instrtype, evid)
            weight_spec = weight_by_key.get(key)
            if weight_spec is not None:
                weight_interp = np.interp(
                    freq_array, weight_spec.freq, weight_spec.data)
                # Sanity check: weights must be in [0, 1]
                if np.any(weight_interp < 0) or np.any(weight_interp > 1):
                    print(
                        f'Warning: {spec.id}: spectral weights outside '
                        '[0, 1] range, renormalizing'
                    )
                    weight_interp = np.clip(weight_interp, 0, None)
                    weight_interp /= np.max(weight_interp)
                weight_total *= weight_interp
                weights_used = True
        # Replace nan data_mag with zeros and apply weights
        spec_interp.data_mag[np.isnan(spec_interp.data_mag)] = 0
        spec_interp.data_mag *= weight_total
        if spec_mean is None:
            spec_mean = spec_interp
        else:
            spec_mean.data_mag += spec_interp.data_mag
    spec_mean.data_mag /= len(res_list)
    spec_mean.stats.data_type = 'mean_residual'
    spec_mean.data = mag_to_moment(spec_mean.data_mag)
    return spec_mean, weights_used


def _compute_mean_residuals(residual_dict, min_spectra=20, use_weights=False):
    """
    Compute mean residuals for each station.

    Parameters
    ----------
    residual_dict : dict
        Dictionary containing residuals for each station.
    min_spectra : int
        Minimum number of spectra to compute residuals (default=20).
    use_weights : bool
        If True, multiply each residual spectrum by its spectral weight
        (``data_type='weight'``) before averaging. See
        :func:`_compute_station_mean` for the formula.
        Falls back to unit weights for spectra or stations without
        weight data (default=False).

    Returns
    -------
    residual_mean : SpectrumStream
        Stream containing mean residuals for each station.
    """
    residual_mean = SpectrumStream()
    for stat_id in sorted(residual_dict.keys()):
        res = residual_dict[stat_id]

        # Separate weights from residuals
        weight_list = [
            s for s in res
            if getattr(s.stats, 'data_type', '') == 'weight'
        ]
        res_list = [
            s for s in res
            if getattr(s.stats, 'data_type', '') != 'weight'
        ]

        if len(res_list) < min_spectra:
            continue
        print(f'Processing station: {stat_id}')

        # Build a lookup for weights by (id, instrtype, event_id)
        weight_by_key = {}
        for w in weight_list:
            evid = w.stats.event.get('event_id')
            key = (w.id, w.stats.instrtype, evid)
            weight_by_key[key] = w

        freqs_min = [spec.freq.min() for spec in res_list]
        freqs_max = [spec.freq.max() for spec in res_list]
        delta_f_min = min(spec.stats.delta for spec in res_list)
        freq_min = min(freqs_min)
        freq_max = max(freqs_max)
        # stop two steps before the maximum frequency,
        # to avoid border effects
        freq_array = np.arange(freq_min, freq_max - delta_f_min, delta_f_min)

        spec_mean, weights_used = _compute_station_mean(
            res_list, weight_by_key, freq_array, use_weights)

        if use_weights:
            if weights_used:
                print(f'{stat_id}: using spectral weights')
            else:
                print(f'{stat_id}: no spectral weights found, '
                      'using unweighted mean')
        spec_mean.stats.software = 'SourceSpec'
        spec_mean.stats.software_version = get_versions()['version']
        residual_mean.append(spec_mean)
    return residual_mean


# ---- PLOTTING UTILITIES


def _compute_global_limits(residual_dict, residual_mean, ymin, ymax):
    """Compute global x and y axis limits from all residuals."""
    global_fmin = np.inf
    global_fmax = -np.inf
    global_ymin = np.inf
    global_ymax = -np.inf
    for spec_mean in residual_mean:
        for spec in residual_dict[spec_mean.id]:
            if getattr(spec.stats, 'data_type', '') == 'weight':
                continue
            if not spec.data_mag.size:
                continue
            global_fmin = min(global_fmin, spec.freq.min())
            global_fmax = max(global_fmax, spec.freq.max())
            global_ymin = min(global_ymin, np.nanmin(spec.data_mag))
            global_ymax = max(global_ymax, np.nanmax(spec.data_mag))
    if ymin is None:
        ymin = global_ymin
    if ymax is None:
        ymax = global_ymax
    # Add 10% padding to frequency range in log space
    log_range = np.log10(global_fmax / global_fmin)
    pad_factor = 10 ** (0.05 * log_range)
    global_fmin /= pad_factor
    global_fmax *= pad_factor
    return global_fmin, global_fmax, ymin, ymax


def _build_weight_lookup(res, use_weights):
    """Separate weights from residuals and build a weight lookup dict."""
    res_list = [
        s for s in res
        if getattr(s.stats, 'data_type', '') != 'weight'
    ]
    if not use_weights:
        return res_list, {}
    weight_list = [
        s for s in res
        if getattr(s.stats, 'data_type', '') == 'weight'
    ]
    weight_by_key = {}
    for w in weight_list:
        evid = w.stats.event.get('event_id')
        key = (w.id, w.stats.instrtype, evid)
        weight_by_key[key] = w
    return res_list, weight_by_key


# ---- PLOTTING


def _plot_weighted_residuals(ax, res_list, weight_by_key):
    """Plot individual residuals color-coded by spectral weight."""
    cmap = mcolors.LinearSegmentedColormap.from_list(
        'Blues_trunc', plt.cm.Blues(np.linspace(0.25, 1, 256)))
    norm = mcolors.Normalize(vmin=0, vmax=1)
    for spec in res_list:
        if not spec.data_mag.size:
            continue
        evid = spec.stats.event.get('event_id')
        key = (spec.id, spec.stats.instrtype, evid)
        weight_spec = weight_by_key.get(key)
        freqs = spec.freq
        if weight_spec is not None:
            weight = np.interp(freqs, weight_spec.freq, weight_spec.data)
            weight = np.clip(weight, 0, None)
            if np.max(weight) > 0:
                weight /= np.max(weight)
        else:
            weight = np.ones_like(freqs)
        points = np.array([freqs, spec.data_mag]).T.reshape((-1, 1, 2))
        segments = np.concatenate([points[:-1], points[1:]], axis=1)
        lc = LineCollection(
            segments, cmap=cmap, norm=norm, alpha=0.5,
            rasterized=True, zorder=20)
        lc.set_array(weight)
        lc.set_linewidth(1.0)
        ax.add_collection(lc)
    # Colorbar inside the plot frame
    axins = ax.inset_axes([0.05, 0.08, 0.3, 0.04])
    cbar = matplotlib.colorbar.ColorbarBase(
        axins, cmap=cmap, norm=norm, orientation='horizontal')
    cbar.ax.text(
        0.5, 0.5, 'Weight', fontsize=8, color='w',
        ha='center', va='center')
    cbar.ax.set_xticks([0, 0.5, 1], ['0', '0.5', '1'], size=8)


def _plot_unweighted_residuals(ax, res_list):
    """Plot individual residuals with uniform color."""
    for spec in res_list:
        if not spec.data_mag.size:
            continue
        ax.semilogx(
            spec.freq, spec.data_mag, color='#4682B4',
            alpha=0.5, linewidth=1.0, zorder=20)


def _plot_residuals(
        residual_dict, residual_mean, outdir,
        ymin=None, ymax=None, runid=None,
        use_weights=False):
    """
    Plot residuals.

    Parameters
    ----------
    residual_dict : dict
        Dictionary containing residuals for each station.
    residual_mean : SpectrumStream
        SpectrumStream containing mean residuals for each station.
    outdir : str
        Output directory.
    ymin : float
        Lower limit of Y axis
        (default: None)
    ymax : float
        Upper limit of Y axis
        (default: None)
    runid : str
        Run ID, to be shown in title
        (default: None)
    use_weights : bool
        If True, color individual residuals by spectral weight using a
        blue colormap and show a colorbar (default: False).
    """
    global_fmin, global_fmax, ymin, ymax = _compute_global_limits(
        residual_dict, residual_mean, ymin, ymax)

    for spec_mean in residual_mean:
        stat_id = spec_mean.id
        res = residual_dict[stat_id]
        figurefile = os.path.join(outdir, f'{stat_id}.res.png')
        fig, ax = plt.subplots(dpi=160)

        res_list, weight_by_key = _build_weight_lookup(res, use_weights)

        if use_weights:
            _plot_weighted_residuals(ax, res_list, weight_by_key)
        else:
            _plot_unweighted_residuals(ax, res_list)

        ax.semilogx(
            spec_mean.freq, spec_mean.data_mag, 'r-', linewidth=2, zorder=30)
        ax.set_xlim(global_fmin, global_fmax)
        ax.set_ylim([ymin, ymax])
        ax.grid(
            True, which='both', linestyle='solid', color='#DDDDDD', zorder=0)
        ax.set_xlabel('frequency (Hz)')
        ax.set_ylabel('residual amplitude (obs - synth) in magnitude units')
        n_res = len(res_list)
        if runid:
            title = f'{stat_id} – runid: {runid} - {n_res} records'
        else:
            title = f'{stat_id} – {n_res} records'
        ax.set_title(title)
        fig.savefig(figurefile, bbox_inches='tight')
        plt.close(fig)
        print(f'Residual plot saved to: {figurefile}')


# ---- MAIN


def run_source_residuals():
    """
    Run source_residuals
    """
    args = _parse_args()
    runid = args.runid
    exclude_subdirs = args.exclude_subdirs
    residual_dict = _read_residuals(
        args.residual_files_dir, runid,
        exclude_subdirs=exclude_subdirs
    )
    if not residual_dict:
        sys.exit(
            'No residuals found. Please check the provided input directory.'
        )

    outdir = args.outdir
    # If runid is not None, create a subdirectory with the runid, unless
    # the outdir name is already the runid
    if runid and os.path.split(outdir)[-1] != runid:
        outdir = os.path.join(outdir, runid)
    if not os.path.exists(outdir):
        os.makedirs(outdir)

    min_spectra = int(args.min_spectra)
    residual_mean = _compute_mean_residuals(
        residual_dict, min_spectra, use_weights=args.weighting)

    if args.plot:
        ymin, ymax = args.yrange
        _plot_residuals(
            residual_dict, residual_mean, outdir,
            ymin=ymin, ymax=ymax, runid=runid,
            use_weights=args.weighting
        )

    # write the mean residuals (the stations corrections)
    res_mean_file = 'residual_mean.hdf5'
    res_mean_file = os.path.join(outdir, res_mean_file)
    if not residual_mean:
        sys.exit(
            'Mean residuals not computed: not enough spectra.\n'
            'Minimum number of spectra ("--min_spectra") currently set to: '
            f'{min_spectra}'
        )
    residual_mean.write(res_mean_file, format='HDF5')
    print(f'Mean station residuals saved to: {res_mean_file}')


def main():
    """Main function."""
    try:
        run_source_residuals()
    except KeyboardInterrupt:
        print('\nInterrupted by user')
        sys.exit(1)


if __name__ == '__main__':
    main()
