# Mock modules which are not essential for the Sphinx environment
# (Source: http://docs.readthedocs.org/en/latest/faq.html)
MOCK_MODULES = [
    'matplotlib',
    'matplotlib.cm',
    'matplotlib.colors',
    'matplotlib.backends',
    'matplotlib.backends.backend_pdf',
    'matplotlib.backends.backend_agg',
    'matplotlib.transforms',
    'matplotlib.patches',
    'matplotlib.path',
    'matplotlib.patheffects',
    'matplotlib.pyplot',
    'matplotlib.ticker',
    'mpl_toolkits',
    'mpl_toolkits.axes_grid1',
    'mpl_toolkits.axes_grid1.axes_divider',
    'numpy',
    'scipy',
    'scipy.integrate', 'scipy.interpolate', 'scipy.optimize',
    'scipy.stats', 'scipy.stats.mstats', 'scipy.signal',
    'scipy.signal._peak_finding_utils',
    'obspy',
    'obspy.core', 'obspy.core.util', 'obspy.core.inventory',
    'obspy.core.event',
    'obspy.imaging', 'obspy.imaging.beachball',
    'obspy.io', 'obspy.io.sac',
    'obspy.io.xseed', 'obspy.io.xseed.utils',
    'obspy.signal', 'obspy.signal.invsim',
    'obspy.signal.konnoohmachismoothing', 'obspy.signal.filter',
    'obspy.signal.util', 'obspy.signal.trigger',
    'obspy.geodetics', 'obspy.taup',
    'PIL', 'tzlocal',
    'cartopy', 'cartopy.crs', 'cartopy.io', 'cartopy.io.img_tiles',
    'cartopy.io.shapereader', 'cartopy.feature',
    'pyproj'
]
